version: '3.4'

services:
  sql.data:
    environment:
      - SA_PASSWORD=Pass@word
      - ACCEPT_EULA=Y
    ports:
      - "5443:1433"    # Important: In a production environment your should remove the external port

  rabbitmq:
    ports:
      - "15673:15672"  # Important: In a production environment your should remove the external port
      - "5673:5672"    # Important: In a production environment your should remove the external port
  scrapper.cache:
    ports:
      - "16379:6379"    # Important: In a production environment your should remove the external port
  tvshows.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - EventBusConnection=${TVSHOWS_AZURE_SERVICE_BUS:-rabbitmq}
      - EventBusUserName=${TVSHOWS_SERVICE_BUS_USERNAME}
      - EventBusPassword=${TVSHOWS_SERVICE_BUS_PASSWORD}   
    ports:
      - "5001:80"
    volumes:
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro

  tvmaze.scrapper:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - ConnectionString=${TVSHOWS_AZURE_REDIS_SCRAPPER_DB:-scrapper.cache}
      - EventBusConnection=${TVSHOWS_AZURE_SERVICE_BUS:-rabbitmq}
      - EventBusUserName=${TVSHOWS_SERVICE_BUS_USERNAME}
      - EventBusPassword=${TVSHOWS_SERVICE_BUS_PASSWORD}          
      - UpdateCheckInterval= 30000
      - RateLimitOccurrences=20
      - RateLimitSeconds=10
      - TVMazeAPIBaseURL=http://api.tvmaze.com/
    ports:
      - "5002:80"
    volumes:
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro

  SampleApiGateway:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5003:80"   
    volumes:
      - ./src/Api/SampleApi:${TVSHOW_OCELOT_VOLUME_SPEC:-/app/configuration}