// <auto-generated />

using System;
using AUTOPAL.RTL.TVMaze.Services.TVShows.API.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;

namespace AUTOPAL.RTL.TVMaze.Services.TVShows.API.Migrations
{
    [DbContext(typeof(TVShowContext))]
    [Migration("20181204225855_BirthdayNullable")]
    partial class BirthdayNullable
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.3-rtm-32065")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("AUTOPOAL.RTL.TVMaze.Services.TVShows.API.Model.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("BirthDate");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<int>("TVMazeId");

                    b.HasKey("Id");

                    b.ToTable("Person");
                });

            modelBuilder.Entity("AUTOPOAL.RTL.TVMaze.Services.TVShows.API.Model.Show", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<int>("TVMazeId");

                    b.Property<long>("Timestamp");

                    b.HasKey("Id");

                    b.ToTable("Show");
                });

            modelBuilder.Entity("AUTOPOAL.RTL.TVMaze.Services.TVShows.API.Model.ShowPerson", b =>
                {
                    b.Property<int>("PersonId");

                    b.Property<int>("ShowId");

                    b.HasKey("PersonId", "ShowId");

                    b.HasIndex("ShowId");

                    b.ToTable("ShowPerson");
                });

            modelBuilder.Entity("AUTOPOAL.RTL.TVMaze.Services.TVShows.API.Model.ShowPerson", b =>
                {
                    b.HasOne("AUTOPOAL.RTL.TVMaze.Services.TVShows.API.Model.Person", "Person")
                        .WithMany("Shows")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("AUTOPOAL.RTL.TVMaze.Services.TVShows.API.Model.Show", "Show")
                        .WithMany("Persons")
                        .HasForeignKey("ShowId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
